title: Huan Phan-Van, Ph.D.
description: Personal academic website of Huan Phan-Van, Ph.D., Assistant Professor of Robotics and Mechatronics Engineering at Randolph College.

# Site Settings

baseurl: ""
url: "https://huantianh.github.io"

# Author Settings

author: Huan Phan-Van
author-img: huan_phanvan.jpg
about-author: "Assistant Professor of Robotics and Mechatronics Engineering at Randolph College. My research interests include time-delay systems, Lyapunov-Krasovskii methods, feedback control, robotics, and mechatronics education."

# Social Links

social-facebook: huantianh
social-github: huantianh
social-linkedin: huanphanvan
social-email: [hphan206@randolphcollege.edu](mailto:hphan206@randolphcollege.edu)

# Disqus

discus-identifier:

# Tracker

analytics:

# Build Settings

markdown: kramdown
plugins:

* jekyll-sitemap
* jekyll-paginate
* jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
