title: Huan Phan-Van Portfolio
description: #> # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://huantianh.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Huan Phan-Van # add your name
author-img: huan_phanvan.jpg # add your photo
about-author: PhD Student at SIUE # add description
social-facebook: huantianh # add your Facebook handle
social-github: Huan Phan Van # add your Github handle
social-linkedin: huanphanvan # add your Linkedin handle
social-email: huphan@siue.edu # add your Email address

# Disqus
discus-identifier: Red # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
