title: Huan Phan-Van Portfolio
description: With over three years of teaching and researching experience in robotics and mechatronics, I am an instructor at Southern Illinois University Edwardsville (SIUE), where I share my passion and knowledge with students and colleagues.
I am passionate about developing innovative and practical solutions for real-world challenges using robotics and mechatronics.

# permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://huantphanvan.me" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Huan Phan-Van # add your name
author-img: huan_phanvan.jpg # add your photo
about-author: Instructor at SIUE # add description
social-facebook: huantianh # add your Facebook handle
social-github: huantianh # add your Github handle
social-linkedin: huanphanvan # add your Linkedin handle
social-email: huphan@siue.edu # add your Email address

# Disqus
discus-identifier: Red # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
